#!/usr/bin/env python

Import("env")

env.acorn_sources = []

# Godot source files
env.add_source_files(env.acorn_sources, "*.cpp")

# Build it all as a library
lib = env.add_library("acorn", env.acorn_sources)
env.Prepend(LIBS=[lib])
